# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b35e45225e26475179acdbe3500722147f06c0203ba753792c1140b87eac25ab5e504da1d43f0fffd09df7db8bb2a3c8d5204ec967bda6da20352746f6c18dda

test:
  secret_key_base: 14ca1bae6bbcf7b83c8973cc890cc8faef9bbee923133e14ddbda07c0fbec511f292328b68048c5e759981322c45a675f98371a6ec7313ed7e289fcff59181a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
